export * as authApi from './auth'
export * as employeeApi from './employee'
export * as attendanceApi from './attendance'
export * as applicationApi from './application'
export * as meetingApi from './meeting'
export * as customerApi from './customer'
export * as adminApi from './admin'
export * as financeApi from './finance'
export * as statisticsApi from './statistics'

